---
name: BlueRiiot2MQTT
version: 0.14.0
slug: blueriiot2mqtt
description: Add-on to translate between Blue Riiots pool API, and HASS via MQTT
arch:
- amd64
- armv7
- aarch64
url: https://github.com/LordMike/MBW.BlueRiiot2MQTT
startup: application
boot: auto
environment:
  EXTRA_CONFIG_FILE: "/data/options.json"
options:
  MQTT:
    Server: REQUIRED
    Username: ''
    Password: ''
  BlueRiiot:
    Username: REQUIRED
    Password: REQUIRED
schema:
  MQTT:
    Server: str
    Port: port?
    Username: str?
    Password: str?
    ClientId: str?
  BlueRiiot:
    Username: str
    Password: str
    Language: list(fr|es|en|nl|de|it|pt|cs)
    DiscoveryInterval: str
    UpdateInterval: str
    UpdateIntervalWhenAllDevicesAsleep: str
    ReportUnchangedValues: bool
    EnableSchedule: bool
  HASS:
    DiscoveryPrefix: str
    TopicPrefix: str
    EnableHASSDiscovery: bool
image: lordmike/blueriiot2mqtt
